### ISSUE TITLE
History does not show payment ID

### ISSUE THREAD

**Issue by M5M400** [monero-project/monero-core#87]
![screenshot from 2016-10-25 13-29-10](https://cloud.githubusercontent.com/assets/22886679/19684959/62cff8d8-9aba-11e6-9873-04c6bec27faf.png)

**Comment by dEBRUYNE-1** [comment]
This is a bit odd. I have been testing this with @medusadigital and back then it worked perfectly. 

Could you try to use an integrated address and see what happens?

Also, which commit did you compile on?

**Comment by medusadigital** [comment]
Yes, we tested that, but it just happend also to me too, so i guess something with recent commits has to be causing it? or we have overseen something and it only shows with incoming/outgoing trx ? 

anyway, seems only to affect integrated addresses. was it an integrated address @M5M400  ?

**Comment by M5M400** [comment]
@dEBRUYNE-1 I was on 05046a5. Now on 08c7ff2, as aparently b74cae4 upwards are broken (src/libwalletqt/WalletManager.cpp:164:35: error: ‘paymentIdFromAddress’ is not a member of ‘Bitmonero::Wallet’). Same behavior.

@medusadigital integrated addresses work as expected. Only transactions using normal addresses affected.

**Comment by taushet** [comment]
FYI, that is an older commit. I changed some of the text (it now reads 'Block height' not 'BlockHeight', for example) in #85.

**Comment by moneromooo-monero** [comment]
Are you sure you have a recent enough monero tree ?

$ git grep paymentIdFromAddress
src/wallet/api/wallet.cpp:std::string Wallet::paymentIdFromAddress(const std::string &str, bool testnet)
src/wallet/wallet2_api.h:    static std::string paymentIdFromAddress(const std::string &str, bool testnet);

**Comment by Jaqueeee** [comment]
@M5M400 are you on os x?
Noticed the build instructions isn't up to date. So you would have to delete the monero folder before running build.sh to ensure you get the current wallet api. Will update those instructions soon.

**Comment by M5M400** [comment]
@moneromooo-monero built everything from scratch. I might have neglected to rebuild the wallet api. Now running on d22e02a.

Sadly, still no payment ID (the 0.1 XMR transaction is the new one - will create another issue for the date sorting not working)

![screenshot from 2016-10-27 15-17-51](https://cloud.githubusercontent.com/assets/22886679/19768621/973f99b2-9c58-11e6-8ef4-0c0ca54385f6.png)

**Comment by moneromooo-monero** [comment]
The GUI won't show my past txes in the first place, so I'm unable to determine whether my recent patches broke this. Revert them if you want to check.

**Comment by medusadigital** [comment]
- Paymend id's regarding new Transactions should be fixed by this: https://github.com/monero-project/monero/pull/1282

- Historical transactions (rebuilding wallet cache) should be fixed by https://github.com/monero-project/monero/pull/1295.

**Comment by medusadigital** [comment]
@M5M400 have time for a retest? seems good to me but i cant test all combinations

**Comment by M5M400** [comment]
@medusadigital what am I doing wrong? pulled current master c9bb2f5; reran get_libwallet_api.sh; make; clean; make; restore wallet from seed (new folderstructure anyway); wallet sync from block 0 -> still not showing historical or new payment IDs...

**Comment by dEBRUYNE-1** [comment]
@M5M400 Do you have a Monero folder present in the same build environment?

**Comment by M5M400** [comment]
@dEBRUYNE-1 @medusadigital I'll be damned. I only ever tested incoming transactions with my mymonero wallet. Now I tested with the CLI wallet and everything works fine. Both classic addresses + payment ID as well as integrated addresses...

![screenshot from 2016-11-09 11-47-58](https://cloud.githubusercontent.com/assets/22886679/20135954/bb7f7b70-a672-11e6-86cc-4e5ecfbbf583.png)

So from where I'm sitting, it seems that there is a bug in mymonero, not in monero-core. can anyone confirm?

**Comment by M5M400** [comment]
is there a reason why this isn't closed already?

**Comment by Jaqueeee** [comment]
@M5M400 Only you can close this afaik. And repo maintainer (i.e @fluffypony) ofc.

**Comment by Jaqueeee** [comment]
please close
